name: Build App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository (master branch)
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: master

      # Set up JDK 17 for Android builds
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Cache Gradle dependencies
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches # Cache the Gradle caches directory
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }} # Generate a key based on OS, Gradle version, and build files
          restore-keys: |
            ${{ runner.os }}-gradle- # Fallback key for older caches

      # Configure Android SDK environment variables
      # Note: Caching the SDK itself is less common than caching Gradle,
      # as installing platforms/build-tools via sdkmanager is usually fast.
      # We'll keep the installation steps.
      - name: Set Android SDK environment variables
        run: |
          echo "ANDROID_HOME=/usr/local/lib/android/sdk" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=/usr/local/lib/android/sdk" >> $GITHUB_ENV
          echo "/usr/local/lib/android/sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH

      # Accept Android SDK licenses
      - name: Accept licenses
        run: yes | sdkmanager --licenses

      # Install required SDK components
      # Install only if the required versions are not present (cached SDK is unlikely here)
      - name: Install additional SDK components
        run: sdkmanager "platforms;android-33" "build-tools;33.0.2"

      # Make Gradle wrapper executable
      - name: Make Gradle executable
        run: chmod +x ./gradlew

      # Build the debug APK
      - name: Build APK
        run: ./gradlew assembleDebug

      # Upload the generated APK as an artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Azusa-APK
          # Corrected path from previous fix
          path: app/build/outputs/apk/debug/*.apk
